### ISSUE TITLE
Strict standards warnings

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/edd-cross-sell-upsell#1]
Shown on cross-sells and upsells report pages:

    Strict standards: Declaration of EDD_CSAU_Reports_Table::bulk_actions() should be compatible with WP_List_Table::bulk_actions($which = '') in /wp-content/plugins/edd-cross-sell-upsell-master/includes/class-reports-table.php on line 339

**Comment by cklosowski** [comment]
Was just coming to report this :+1:

**Comment by pippinsplugins** [comment]
Fixed in #7.
