### ISSUE TITLE
Items can be shown in upsell even when in the cart

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-cross-sell-upsell#11]
Imagine you have two products, X and Y.

X has an upsell to Y. When X is in the cart, the upsell for Y should be shown (and is). Now add Y to the cart. The upsell to Y is still shown because X is still in the cart.

See this ticket: https://secure.helpscout.net/conversation/326211293/54171/?folderId=180505

**Comment by SDavisMedia** [comment]
I've got a ticket for the same thing: https://secure.helpscout.net/conversation/358531746/0/

**Comment by pippinsplugins** [comment]
@SDavisMedia PR submitted. Could you give that a test please?

**Comment by SDavisMedia** [comment]
@pippinsplugins that does the trick for cross-sells on checkout but not single download upsells. Not sure if that was intentional or not. If not, I've committed a fix for that for your review. If unneeded, revert and your original commit worked just fine. :+1:

**Comment by pippinsplugins** [comment]
Looks good to me! Merging and deploying.
