### ISSUE TITLE
Reports not working

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-cross-sell-upsell#6]
We've had a report that none of the reporting in the plugin is working.

https://secure.helpscout.net/conversation/221019628/37092/?folderId=180505

**Comment by pippinsplugins** [comment]
@sumobi could you work on tracking this down?

**Comment by sumobi** [comment]
@pippinsplugins looking...

**Comment by sumobi** [comment]
@easydigitaldownloads/core-devs Ready for testing if anyone can

**Comment by pippinsplugins** [comment]
@sumobi I just tested this and it does not appear to be working. I made a purchase that had both a cross sell and an upsell but neither show in reports.

**Comment by wordmaid** [comment]
I also gave this a test and it worked correctly. An upsell was recorded in the payment history, and it was visible in reports when I changed the view to to show Upsells.

**Comment by pippinsplugins** [comment]
Alrighty then, something is weird on my end. Let's go ahead and merge and deploy @sumobi

**Comment by sumobi** [comment]
Will do soon, just waiting to hear back from customer
